// app state
export const SAVINGS_GOAL_LOADING = 'SAVINGS_GOAL_LOADING';
export const SAVINGS_GOAL_LOADED = 'SAVINGS_GOAL_LOADED';
export const SAVINGS_GOAL_FAILED = 'SAVINGS_GOAL_FAILED';
export const SAVINGS_GOAL_UPDATED = 'SAVINGS_GOAL_UPDATED';

// savings API
export const SAVINGS_API_LOADING = 'SAVINGS_API_LOADING';
export const SAVINGS_API_SUCCESS = 'SAVINGS_API_SUCCESS';
export const SAVINGS_API_FAIL = 'SAVINGS_API_FAIL';

// create new savings goal
export const CREATE_NEW_SAVINGS_GOAL = 'CREATE_NEW_SAVINGS_GOAL';
export const NEW_SAVINGS_GOAL_SUCCESS = 'NEW_SAVINGS_GOAL_SUCCESS';
export const NEW_SAVINGS_GOAL_FAIL = 'NEW_SAVINGS_GOAL_FAIL';
