export const SAVINGS_GOAL_LOADING = 'SAVINGS_GOAL_LOADING';
export const SAVINGS_GOAL_LOADED = 'SAVINGS_GOAL_LOADED';
export const SAVINGS_GOAL_FAILED = 'SAVINGS_GOAL_FAILED';
export const SAVINGS_GOAL_UPDATED = 'SAVINGS_GOAL_UPDATED';