export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_FAILED = 'HOME_PAGE_FAILED';
export const FIREBASE_RETRIEVED_EMAIL_UID = 'FIREBASE_RETRIEVED_EMAIL_UID';
