export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const TRANSACTIONS_LOADED = 'TRANSACTIONS_LOADED';
export const TRANSACTIONS_FAILED = 'TRANSACTIONS_FAILED';
export const TRANSACTIONS_UPDATED = 'TRANSACTIONS_UPDATED';

export const TRANSFER_TO_SAVINGS = 'TRANSFER_TO_SAVINGS';